### ISSUE TITLE
NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by MARDAScience** [radiantearth/mlhub-tutorials#31]
Following your excellent API notebook. The last cell gives me the following error

`NoCredentialsError: Unable to locate credentials`

Same error with different (valid) arguments

Is there something obvious I am missing?

Python 3.7.6 on Ubuntu 20.04

Thanks

**Comment by MARDAScience** [comment]
Should have said, it's the last cell of `radiant-mlhub-bigearthnet.ipynb` where I see this issue

**Comment by kbgg** [comment]
Hi @MARDAScience,

You're getting this error because you are attempting to download assets from S3 but the boto3 library can not find your AWS credentials. If you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables with your access key ID and secret access key, respectively, you shouldn't receive this error.

Best,
Kevin

**Comment by MARDAScience** [comment]
Hi Kevin,
Thanks, that makes sense.
-D
