### ISSUE TITLE
limit parameter value to download all data

### ISSUE THREAD

**Issue by michaeltrs** [radiantearth/mlhub-tutorials#48]
Hi, I have noticed that setting a value too large for the "limit" parameter leads to a Response [503] error. 

        r = requests.get(f'{API_BASE}/collections/{collectionId}/items?key={API_KEY}&limit=%d' % i)

Setting a small value obsiously leads to getting only part of the data. What would be a way to download all data? Also what would be a way of finding the amount of data samples in a given dataset?

Many thanks,
Michael

**Comment by duckontheweb** [comment]
Your timing is impeccable! We are very close to an alpha release of the `radiant-mlhub` Python client (see radiantearth/radiant-mlhub#19) that will make this kind of thing much easier. We will also be updating the notebooks in this repo to use that Python client instead of the `requests` library directly.

In the meantime, here are some answers to your questions...

> I have noticed that setting a value too large for the "limit" parameter leads to a Response [503] error.

The `/collections/{collectionId}/items` endpoint is paginated and the `limit` parameter controls the maximum number of features returned *per page*. [Here](https://github.com/radiantearth/radiant-mlhub/blob/dev/radiant_mlhub/session.py#L153-L174) is how we handle looping over all the pages in the new client, but the basic idea is:

1) Look for a `"links"` property in the response (this will be a list of dicts if it exists)
2) Within that list, look for an dict with a `"rel"` value of `"next"`
3) Grab the `"href"` property from that dict and make a request to that URL to get the next page of results

*For very large collections like `bigearthnet_v1_source` this is going to take forever to loop through all of the items. See the next point for a better way to get all of the collection assets.*

> What would be a way to download all data?

We have recently begun creating tar archives for each collection that include all assets associated with that collection. You can download these archives using the `{API_BASE}/archive/{collectionId}` endpoint. 

*Note that we are still in the process of generating these archives, so they may not exist for many of the collections.* If an archive doesn't exist yet you'll get a `404` response from that endpoint, and you can just try again later to see if it's ready. We will be putting out a blog post describing the structure of these archives and how to use the endpoint in the near future.

> Also what would be a way of finding the amount of data samples in a given dataset?

Right now, the best way to get this information is actually using the `/search` endpoint. It's a bit roundabout, but the following will give you an item count for the given collection:

```python
r = requests.get(f'{API_BASE}/search?key={API_KEY}&limit=0&collections={collectionId}')
item_count = r.json()['context']['matched']
```

Based on this request, we are thinking that we will add an `item_count` property to the [`Collection` class](https://github.com/radiantearth/radiant-mlhub/blob/dev/radiant_mlhub/models.py#L22) in the new client library to make it easier to get this info.

Hope that helps!

**Comment by duckontheweb** [comment]
@michaeltrs An alpha version (`v0.1.0`) of the [`radiant_mlhub` client is now available [on PyPi](https://pypi.org/project/radiant-mlhub/). This version includes methods for downloading collection archives (see [this section](https://radiant-mlhub.readthedocs.io/en/latest/collections.html#downloading-a-collection) of the docs), but does not yet include an `item_count` property on the `Collection` class (look for this in a future release).

**Comment by michaeltrs** [comment]
@duckontheweb thank you very much for a detailed response and for the update. I have had a look at the documents and tested the new python client and it is indeed much easier to work with
