### ISSUE TITLE
Missing Labels for South Africa Crop Type Competition

### ISSUE THREAD

**Issue by zwxlyy1995** [radiantearth/mlhub-tutorials#78]
Hi, 

I downloaded the `South Africa Crop Type Competition` dataset for research purpose, but I can't find the corresponding ground truth information in TEST set.

Specifically, there are two TIF files in TRAIN set for each parcel : `field_ids.tif` and `labels.tif`. but corresponding `labels.tif` is missing for each parcel in TEST set.  I know the dataset was uploaded to MLHub before the end date of two related competitions :[spot-the-crop-xl-challenge](https://github.com/radiantearth/spot-the-crop-xl-challenge) and [spot-the-crop-challenge](https://github.com/radiantearth/spot-the-crop-challenge), when the ground truth for TEST set should not be revealed. 

Now, both related competitions were ended for almost one year. I wonder if the corresponding ground truth could be available on MLHub.

Reply would be appreciated, Thanks.

**Comment by KennSmithDS** [comment]
HI @zwxlyy1995 on the Radiant MLHub website, you should be able to see the collections for both `train` and `test` portions of the published dataset [here](https://mlhub.earth/data/ref_south_africa_crops_competition_v1). I am uncertain what state the dataset was in from the competitions you cited. Often the version of the datasets we publish have undergone some required changes in order to be published on Radiant MLHub from the time a dataset is originally released for a competition.

For both train and test labels, you will see a `field_ids.tif` and a `labels.tif` as well as `labels.json` for different reasons. Each label has multiple linked source assets across the dataset because of the time series. Then the source imagery collections will give you either the `polarization` bands VV, VH... or `eo` bands B01, B02... (depending if it's Sentinel-1 or Sentinel-2 respectively).

If you download the dataset `.tar.gz` files either from the website directly or using our Python client `radiant_mlhub`, you will have the labels and ground truth together. I'm going to close the ticket for now but please feel free to reopen if you have further issues/concerns.

**Comment by zwxlyy1995** [comment]
Hi @KennSmithDS , I still can't find `labels.tif`  in test set  for [South Africa Crop Type Competition](https://mlhub.earth/data/ref_south_africa_crops_competition_v1). No matter it's downloaded directly or by python script.
![image](https://user-images.githubusercontent.com/45357451/201262524-8b456cd8-85ad-4e56-acbe-b52c358c989b.png)
